### ISSUE TITLE
Error: Attempt to apply non-function

### ISSUE THREAD

**Issue by JesseGarcia562** [eliocamp/metamer#3]
Hello, 

I try to run your first example of code found at your github for this package under the Examples headline. One error I consistently get is: 
![image](https://user-images.githubusercontent.com/26375565/54167119-7e99d400-4425-11e9-90bd-aa299561e07f.png)
 

I tried to see where the issue might be. I think it has something to do with this line in  the metamerize function:
p_bar$terminate()

![image](https://user-images.githubusercontent.com/26375565/54167193-c587c980-4425-11e9-9bbc-5cc3f9bf4eb4.png)

As far as I can tell, after running "p_bar$terminate()" the function throws an error and quits out. I'm not really experienced in public and private methods in R so I couldn't figure out much more.  

Here is the code I attempted to run: 

library(metamer)
\# Start with the datasaurus
\# install.packages("datasauRus")
start <- subset(datasauRus::datasaurus_dozen, dataset == "dino")
start$dataset <- NULL

\# And we want to preserve means and correlation
mean_cor <- delayed_with(mean(x), mean(y), cor(x, y)) 
N <- 20000
set.seed(42) # To make results reproducible
metamers <- metamerize(start, preserve = mean_cor, N = N) \#The error occurs here after finishing generating metamers and the progress bar ends
print(metamers)
\#> List of 12782 metamers

**Comment by eliocamp** [comment]
Weird. I can't reproduce the error. Do you have the latest version of progress? If the problem is from that line, then it might be a problem with that package? 
Do you downloaded the latest version of metamer from github?

**Comment by JesseGarcia562** [comment]
Ah that was it! I had version 1.1.2 of the "progress" package. Installing the latest version fixed the issue. Sorry I should've checked that sooner! I thought you created "p_bar" so I didn't even think to check that could be a problem. Thanks.
